import dotenv from "dotenv";
dotenv.config();

import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL environment variable is not set");
}
console.log("Connecting to:", connectionString.substring(0, 40) + "...");

const pool = new pg.Pool({ connectionString, ssl: { rejectUnauthorized: false } });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const books = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    description: "A gripping, heart-wrenching tale of racial injustice in the American South, seen through the eyes of young Scout Finch. This Pulitzer Prize-winning novel explores themes of moral growth, compassion, and the destruction of innocence.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    genre: "Classic",
    publisher: "Harper Perennial",
    publishedYear: 1960,
    pageCount: 336,
    language: "English",
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    description: "A dystopian masterpiece about a totalitarian regime that controls every aspect of life, including thought itself. Winston Smith's rebellion against Big Brother remains one of literature's most powerful warnings about the dangers of oppressive government.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    genre: "Sci-Fi",
    publisher: "Signet Classics",
    publishedYear: 1949,
    pageCount: 328,
    language: "English",
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    description: "Set in the Jazz Age on Long Island, this novel delves into themes of decadence, idealism, social upheaval, and excess, creating a portrait of the American Dream's promise and failure.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    genre: "Classic",
    publisher: "Scribner",
    publishedYear: 1925,
    pageCount: 180,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9780141439518",
    description: "A witty and romantic novel following Elizabeth Bennet as she navigates love, class, and family expectations in Regency-era England. Austen's sharp social commentary remains remarkably relevant today.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    genre: "Romance",
    publisher: "Penguin Classics",
    publishedYear: 1813,
    pageCount: 432,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "9780547928227",
    description: "Bilbo Baggins, a comfort-loving hobbit, is swept into an epic quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. A timeless adventure that introduced millions to Middle-earth.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    genre: "Fantasy",
    publisher: "Mariner Books",
    publishedYear: 1937,
    pageCount: 300,
    language: "English",
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    isbn: "9780590353427",
    description: "The book that launched a global phenomenon. Young Harry Potter discovers he's a wizard and enters Hogwarts School of Witchcraft and Wizardry, where he uncovers the truth about his parents and faces the dark wizard Voldemort.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg",
    genre: "Fantasy",
    publisher: "Scholastic",
    publishedYear: 1997,
    pageCount: 309,
    language: "English",
    totalCopies: 4,
    availableCopies: 3,
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "9780316769488",
    description: "Holden Caulfield's iconic narrative of teenage alienation and loss of innocence in 1950s New York City. This coming-of-age classic continues to resonate with readers of every generation.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
    genre: "Fiction",
    publisher: "Little, Brown and Company",
    publishedYear: 1951,
    pageCount: 234,
    language: "English",
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    isbn: "9780441013593",
    description: "Set on the desert planet Arrakis, this epic science fiction saga follows young Paul Atreides as he navigates political intrigue, ecological wonder, and destiny. Often considered the greatest science fiction novel ever written.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
    genre: "Sci-Fi",
    publisher: "Ace Books",
    publishedYear: 1965,
    pageCount: 688,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    isbn: "9780618640157",
    description: "The definitive fantasy epic. Frodo Baggins must destroy the One Ring in the fires of Mount Doom to save Middle-earth from the Dark Lord Sauron. A sweeping tale of friendship, sacrifice, and the triumph of good over evil.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
    genre: "Fantasy",
    publisher: "Mariner Books",
    publishedYear: 1954,
    pageCount: 1178,
    language: "English",
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    isbn: "9780060850524",
    description: "A chilling vision of a future society where humans are genetically engineered and socially conditioned for a stable but soulless existence. Huxley's prophetic novel challenges our ideas about freedom, happiness, and technology.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    genre: "Sci-Fi",
    publisher: "Harper Perennial",
    publishedYear: 1932,
    pageCount: 288,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "The Da Vinci Code",
    author: "Dan Brown",
    isbn: "9780307474278",
    description: "A murder inside the Louvre and clues in Da Vinci paintings lead to the discovery of a religious mystery protected by a secret society for two thousand years. A fast-paced intellectual thriller that became a global phenomenon.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
    genre: "Thriller",
    publisher: "Anchor",
    publishedYear: 2003,
    pageCount: 489,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    description: "A magical story about Santiago, an Andalusian shepherd boy who journeys to the Egyptian pyramids in search of a treasure. Along the way, he learns to listen to his heart and follow his dreams.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
    genre: "Fiction",
    publisher: "HarperOne",
    publishedYear: 1988,
    pageCount: 197,
    language: "English",
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    description: "A groundbreaking narrative of humanity's creation and evolution that explores how biology and history have defined us and enhanced our understanding of what it means to be human.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    genre: "Non-Fiction",
    publisher: "Harper",
    publishedYear: 2011,
    pageCount: 464,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    description: "A revolutionary guide to building good habits and breaking bad ones. Clear reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg",
    genre: "Self-Help",
    publisher: "Avery",
    publishedYear: 2018,
    pageCount: 320,
    language: "English",
    totalCopies: 3,
    availableCopies: 2,
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    isbn: "9780345391803",
    description: "Seconds before Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect. A wildly funny and satirical science fiction classic.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg",
    genre: "Sci-Fi",
    publisher: "Del Rey",
    publishedYear: 1979,
    pageCount: 224,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "9780374533557",
    description: "Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think: System 1, which is fast and intuitive, and System 2, which is slow and deliberate.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg",
    genre: "Non-Fiction",
    publisher: "Farrar, Straus and Giroux",
    publishedYear: 2011,
    pageCount: 499,
    language: "English",
    totalCopies: 1,
    availableCopies: 1,
  },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    isbn: "9780307454546",
    description: "A journalist and a young female hacker investigate a decades-old disappearance in this riveting thriller. A gripping tale of corruption, family secrets, and unlikely alliances set in Sweden.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg",
    genre: "Mystery",
    publisher: "Vintage Crime/Black Lizard",
    publishedYear: 2005,
    pageCount: 672,
    language: "English",
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    title: "Gone Girl",
    author: "Gillian Flynn",
    isbn: "9780307588371",
    description: "On their fifth wedding anniversary, Nick Dunne's wife Amy disappears. Under pressure from the police and media, Nick's portrait of a blissful union begins to crumble. A dark and twisted psychological thriller.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg",
    genre: "Thriller",
    publisher: "Crown",
    publishedYear: 2012,
    pageCount: 432,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "9780553380163",
    description: "Stephen Hawking's landmark work explores the universe's most fundamental questions: Where did we come from? Why is the universe the way it is? A brilliant guide to the cosmos for non-scientists.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg",
    genre: "Science",
    publisher: "Bantam",
    publishedYear: 1988,
    pageCount: 212,
    language: "English",
    totalCopies: 1,
    availableCopies: 1,
  },
  {
    title: "The Hunger Games",
    author: "Suzanne Collins",
    isbn: "9780439023481",
    description: "In a dark vision of the near future, sixteen-year-old Katniss Everdeen volunteers to take her younger sister's place in the Hunger Games, a televised fight to the death. A thrilling tale of survival and rebellion.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780439023481-L.jpg",
    genre: "Sci-Fi",
    publisher: "Scholastic Press",
    publishedYear: 2008,
    pageCount: 374,
    language: "English",
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    isbn: "9781594631931",
    description: "A haunting tale of friendship, betrayal, and redemption set against the backdrop of Afghanistan's turbulent history. Amir's journey from Kabul to America and back is both deeply personal and universally resonant.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    genre: "Fiction",
    publisher: "Riverhead Books",
    publishedYear: 2003,
    pageCount: 371,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "The Shining",
    author: "Stephen King",
    isbn: "9780307743657",
    description: "Jack Torrance's new job as the caretaker of the Overlook Hotel is the perfect chance for a fresh start. But as the harsh winter weather sets in, the hotel's sinister past starts to come alive. A masterpiece of horror.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780307743657-L.jpg",
    genre: "Horror",
    publisher: "Anchor",
    publishedYear: 1977,
    pageCount: 447,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "Educated",
    author: "Tara Westover",
    isbn: "9780399590504",
    description: "A remarkable memoir of a woman who grew up in a survivalist family in the mountains of Idaho and went on to earn a PhD from Cambridge University. A story about the transformative power of education.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
    genre: "Biography",
    publisher: "Random House",
    publishedYear: 2018,
    pageCount: 334,
    language: "English",
    totalCopies: 2,
    availableCopies: 1,
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "9780140449334",
    description: "The private thoughts of the Roman Emperor Marcus Aurelius offer timeless wisdom on duty, virtue, and resilience. These personal writings are considered one of the greatest works of Stoic philosophy.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780140449334-L.jpg",
    genre: "Philosophy",
    publisher: "Penguin Classics",
    publishedYear: 180,
    pageCount: 254,
    language: "English",
    totalCopies: 1,
    availableCopies: 1,
  },
  {
    title: "And Then There Were None",
    author: "Agatha Christie",
    isbn: "9780062073488",
    description: "Ten strangers are lured to an isolated island mansion, where one by one they begin to die according to a sinister nursery rhyme. Agatha Christie's best-selling mystery novel and the world's best-selling mystery.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg",
    genre: "Mystery",
    publisher: "William Morrow Paperbacks",
    publishedYear: 1939,
    pageCount: 272,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
  {
    title: "Project Hail Mary",
    author: "Andy Weir",
    isbn: "9780593135204",
    description: "Ryland Grace is the sole survivor on a desperate, last-chance mission to save Earth from an extinction-level threat. With his memories slowly returning, he realizes he's lightyears from home. A thrilling and heartwarming sci-fi adventure.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg",
    genre: "Sci-Fi",
    publisher: "Ballantine Books",
    publishedYear: 2021,
    pageCount: 496,
    language: "English",
    totalCopies: 3,
    availableCopies: 3,
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    isbn: "9780062457714",
    description: "A refreshingly honest self-help book that argues for a more grounded approach to life by learning to focus on what truly matters. Manson's counterintuitive approach challenges conventional positive thinking.",
    coverImage: "https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg",
    genre: "Self-Help",
    publisher: "Harper",
    publishedYear: 2016,
    pageCount: 224,
    language: "English",
    totalCopies: 2,
    availableCopies: 2,
  },
];

async function main() {
  console.log("Seeding database...");

  for (const book of books) {
    await prisma.book.upsert({
      where: { isbn: book.isbn },
      update: book,
      create: book,
    });
  }

  console.log(`Seeded ${books.length} books!`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
